services:
  # PostgreSQL Database
  demo_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=demo
    volumes:
      - demo_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

# Volumes to persist database data
volumes:
  demo_db_data:
